controller_manager_ns: moveit_simple_controller_manager
controller_list:
  - name: "jaco_arm_driver/jaco_arm_controller"
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints: [jaco_joint_1, jaco_joint_2, jaco_joint_3, jaco_joint_4, jaco_joint_5, jaco_joint_6]
